from enum import Enum


class AllowanceChargeReasonCode(Enum):
    BONUS_FOR_WORKS_AHEAD_OF_SCHEDULE = 41
    OTHER_BONUS = 42
    MANUFACTURERS_CONSUMER_DISCOUNT = 60
    DUE_TO_MILITARY_STATUS = 62
    DUE_TO_WORK_ACCIDENT = 63
    SPECIAL_AGREEMENT = 64
    PRODUCTION_ERROR_DISCOUNT = 65
    NEW_OUTLET_DISCOUNT = 66
    SAMPLE_DISCOUNT = 67
    END_OF_RANGE_DISCOUNT = 68
    INCOTERM_DISCOUNT = 70
    POINT_OF_SALE_THRESHOLD_ALLOWANCE = 71
    MATERIAL_SURCHARGE_OR_DEDUCTION = 88
    DISCOUNT = 95
    SPECIAL_REBATE = 100
    FIXED_LONG_TERM = 102
    TEMPORARY = 103
    STANDARD = 104
    YEARLY_TURNOVER = 105
