from enum import Enum


class InvoiceTypeCode(Enum):
    REQUEST_FOR_PAYMENT = 71
    DEBIT_NOTE_GOODS_SERVICES = 80
    METERED_SERVICES_INVOICE = 82
    DEBIT_NOTE_FINANCIAL_ADJUSTMENTS = 84
    TAX_NOTIFICATION = 102
    FINAL_PAYMENT_REQUEST_BASED_ON_COMPLETION_OF_WORK = 218
    PAYMENT_REQUEST_FOR_COMPLETED_UNITS = 219
    COMMERCIAL_INVOICER_WITH_PACKING_LIST = 331
    COMMERCIAL_INVOICE = 380
    COMMISSION_NOTE = 382
    DEBIT_NOTE = 383
    PREPAYMENT_INVOICE = 386
    TAX_INVOICE = 388
    FACTORED_INVOICE = 393
    CONSIGNMENT_INVOICE = 395
    FORWARDERS_INVOICER_DISCREPANCY_REPORT = 553
    INSURERS_INVOICE = 575
    FORWARDERS_INVOICE = 623
    FREIGHT_INVOICE = 780
    CLAIM_NOTIFICATION = 817
    CONSULAR_INVOICE = 870
    PARTIAL_CONSTRUCTION_INVOICE = 875
    PARTIAL_FINAL_CONSTRUCTION_INVOICE = 876
    FINAL_CONSTRUCTION_INVOICE = 877
