from enum import StrEnum


class TaxCategoryCode(StrEnum):
    VAT_REVERSE_CHARGE = "AE"
    EXEMPT_FROM_TAX = "E"
    STANDARD_RATE = "S"
    ZERO_RATED_GOODS = "Z"
    FREE_EXPORT_ITEM = "G"
    SERVICES_OUTSIDE_SCOPE = "O"
    VAT_EXEMPT_EEA_INTRA_COMMUNITY_SUPPLY_GOODS_AND_SERVICES = "K"
    CANARY_ISLANDS_GENERAL_INDIRECT_TAX = "L"
    CEUTA_MELILLA_TAX_PRODUCTION_SERVICES_AND_IMPORTATION = "M"
    TRANSFERRED_VAT = "B"
